"""OpenSCAD data file writer with registry pattern."""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Any, Callable

HEADER = "// Auto-generated by mug-generator — do not edit\n\n"

# Registry of emitters: name → function(data, output_dir)
_emitters: dict[str, Callable[[dict[str, Any], Path], None]] = {}


def emitter(name: str):
    """Decorator to register an emitter function."""
    def wrapper(fn: Callable[[dict[str, Any], Path], None]):
        _emitters[name] = fn
        return fn
    return wrapper


def _format_point_2d(pt: list[float] | tuple[float, ...]) -> str:
    return f"[{pt[0]:.6f}, {pt[1]:.6f}]"


def _format_point_3d(pt: list[float] | tuple[float, ...]) -> str:
    return f"[{pt[0]:.6f}, {pt[1]:.6f}, {pt[2]:.6f}]"


def _is_closed(profile: list) -> bool:
    """Check if a profile's last point duplicates the first."""
    if len(profile) < 2:
        return False
    first, last = profile[0], profile[-1]
    return abs(first[0] - last[0]) < 1e-6 and abs(first[1] - last[1]) < 1e-6


def _emit_profile_array(name: str, profile: list, output_dir: Path, filename: str) -> None:
    """Emit a 2D profile array to a .scad file.

    If the last point duplicates the first (closed path), it is stripped
    since OpenSCAD's polygon() closes automatically.
    """
    pts = profile[:-1] if _is_closed(profile) else profile
    lines = [HEADER]
    lines.append(f"{name} = [\n")
    for i, pt in enumerate(pts):
        comma = "," if i < len(pts) - 1 else ""
        lines.append(f"  {_format_point_2d(pt)}{comma}\n")
    lines.append("];\n")
    (output_dir / filename).write_text("".join(lines))


@emitter("mug_body_profile")
def _emit_mug_body_profile(data: dict[str, Any], output_dir: Path) -> None:
    """Emit mug_body_profile.scad — single closed cross-section."""
    _emit_profile_array(
        "mug_body_profile", data["mug_body_profile"],
        output_dir, "mug_body_profile.scad",
    )


@emitter("handle_stations")
def _emit_handle_stations(data: dict[str, Any], output_dir: Path) -> None:
    """Emit handle_stations.scad."""
    stations = data["handle_stations"]  # list of list of [x,y,z]
    lines = [HEADER]
    if not stations:
        lines.append("handle_stations = [];\n")
    else:
        lines.append("handle_stations = [\n")
        for si, poly in enumerate(stations):
            lines.append("  [\n")
            for pi, pt in enumerate(poly):
                comma = "," if pi < len(poly) - 1 else ""
                lines.append(f"    {_format_point_3d(pt)}{comma}\n")
            comma = "," if si < len(stations) - 1 else ""
            lines.append(f"  ]{comma}\n")
        lines.append("];\n")

    (output_dir / "handle_stations.scad").write_text("".join(lines))


@emitter("handle_path")
def _emit_handle_path(data: dict[str, Any], output_dir: Path) -> None:
    """Emit handle_path.scad (debug centroids)."""
    if "handle_path" not in data:
        return
    path = data["handle_path"]  # list of [x,y,z]
    lines = [HEADER]
    if not path:
        lines.append("handle_path = [];\n")
    else:
        lines.append("handle_path = [\n")
        for i, pt in enumerate(path):
            comma = "," if i < len(path) - 1 else ""
            lines.append(f"  {_format_point_3d(pt)}{comma}\n")
        lines.append("];\n")

    (output_dir / "handle_path.scad").write_text("".join(lines))


@emitter("mug_params")
def _emit_mug_params(data: dict[str, Any], output_dir: Path) -> None:
    """Emit mug_params.scad with OpenSCAD parameters."""
    params = data["mug_params"]  # dict with fn, fa, fs, bbox, etc.
    lines = [HEADER]

    if params.get("fn", 0) > 0:
        lines.append(f"$fn = {params['fn']};\n")
    else:
        lines.append(f"$fa = {params.get('fa', 12)};\n")
        lines.append(f"$fs = {params.get('fs', 2)};\n")

    if "bbox" in params:
        bb = params["bbox"]
        lines.append(f"mug_bbox = [{_format_point_3d(bb[0])}, {_format_point_3d(bb[1])}];\n")

    lines.append(f"handle_enabled = {'true' if params.get('handle_enabled') else 'false'};\n")

    if "axis_x" in params:
        lines.append(f"mug_axis_x = {params['axis_x']:.6f};\n")

    if "clay_shrinkage_pct" in params:
        lines.append(f"clay_shrinkage_pct = {params['clay_shrinkage_pct']:.1f};\n")

    # Mould parameters
    for key in ("plaster_thickness", "wall_thickness", "natch_radius"):
        if key in params:
            lines.append(f"{key} = {params[key]:.6f};\n")

    # Body profile indices
    if "body_foot_idx" in params:
        lines.append(f"body_foot_idx = {params['body_foot_idx']};\n")
    if "filler_tube_height" in params:
        lines.append(f"filler_tube_height = {params['filler_tube_height']:.6f};\n")

    # Funnel parameters
    for key in ("funnel_wall_angle", "funnel_wall", "flange_width",
                 "breather_hole_dia"):
        if key in params:
            lines.append(f"{key} = {params[key]:.6f};\n")

    if "breather_hole_count" in params:
        lines.append(f"breather_hole_count = {params['breather_hole_count']};\n")

    if "mould_type" in params:
        lines.append(f"mould_type = {params['mould_type']};\n")

    for key in ("foot_concavity_z", "foot_concavity_radius"):
        if key in params:
            lines.append(f"{key} = {params[key]:.6f};\n")

    # Maker's mark parameters
    lines.append(f"mark_enabled = {'true' if params.get('mark_enabled') else 'false'};\n")
    lines.append(f"mark_depth = {params.get('mark_depth', 1.0):.6f};\n")
    lines.append(f"mark_inset = {'true' if params.get('mark_inset', True) else 'false'};\n")
    lines.append(f"mark_draft_angle = {params.get('mark_draft_angle', 45.0):.6f};\n")
    lines.append(f"mark_layer_height = {params.get('mark_layer_height', 0.2):.6f};\n")

    (output_dir / "mug_params.scad").write_text("".join(lines))


@emitter("mark_polygon")
def _emit_mark_polygon(data: dict[str, Any], output_dir: Path) -> None:
    """Emit mark_polygon.scad with flat points + paths arrays.

    OpenSCAD's ``polygon(points, paths)`` handles even-odd fill
    natively, so we emit a single flat points array and a paths
    array of index lists (one per subpath).  This avoids the
    skin() + difference() approach that produced non-manifold meshes.
    """
    polys = data.get("mark_polygons")
    lines = [HEADER]

    if not polys:
        lines.append("mark_points = [];\n")
        lines.append("mark_paths = [];\n")
    else:
        # Flatten all polygons into one points array, build paths
        all_pts: list[tuple[float, float]] = []
        paths: list[list[int]] = []
        for poly in polys:
            pts = poly[:-1] if _is_closed(poly) else poly
            start = len(all_pts)
            path_indices = list(range(start, start + len(pts)))
            all_pts.extend(pts)
            paths.append(path_indices)

        lines.append("mark_points = [\n")
        for i, pt in enumerate(all_pts):
            comma = "," if i < len(all_pts) - 1 else ""
            lines.append(f"  {_format_point_2d(pt)}{comma}\n")
        lines.append("];\n")

        lines.append("mark_paths = [\n")
        for i, path in enumerate(paths):
            comma = "," if i < len(paths) - 1 else ""
            idx_str = ", ".join(str(j) for j in path)
            lines.append(f"  [{idx_str}]{comma}\n")
        lines.append("];\n")

    (output_dir / "mark_polygon.scad").write_text("".join(lines))


@emitter("static_files")
def _emit_static_files(data: dict[str, Any], output_dir: Path) -> None:
    """Copy static .scad files from the bundled scad/ directory."""
    scad_src = Path(__file__).resolve().parent.parent / "scad"
    if not scad_src.is_dir():
        return

    for src_file in scad_src.rglob("*.scad"):
        rel = src_file.relative_to(scad_src)
        dst = output_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_file, dst)


def run_all_emitters(data: dict[str, Any], output_dir: str | Path) -> list[str]:
    """Run all registered emitters.

    Args:
        data: Dict containing keys expected by each emitter.
        output_dir: Directory to write output files.

    Returns:
        List of emitter names that were run.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    ran = []
    for name, fn in _emitters.items():
        fn(data, out)
        ran.append(name)
    return ran
