"""OpenSCAD data file writer with registry pattern."""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Any, Callable

HEADER = "// Auto-generated by mug-generator — do not edit\n\n"

# Registry of emitters: name → function(data, output_dir)
_emitters: dict[str, Callable[[dict[str, Any], Path], None]] = {}


def emitter(name: str):
    """Decorator to register an emitter function."""
    def wrapper(fn: Callable[[dict[str, Any], Path], None]):
        _emitters[name] = fn
        return fn
    return wrapper


def _format_point_2d(pt: list[float] | tuple[float, ...]) -> str:
    return f"[{pt[0]:.6f}, {pt[1]:.6f}]"


def _format_point_3d(pt: list[float] | tuple[float, ...]) -> str:
    return f"[{pt[0]:.6f}, {pt[1]:.6f}, {pt[2]:.6f}]"


def _is_closed(profile: list) -> bool:
    """Check if a profile's last point duplicates the first."""
    if len(profile) < 2:
        return False
    first, last = profile[0], profile[-1]
    return abs(first[0] - last[0]) < 1e-6 and abs(first[1] - last[1]) < 1e-6


def _emit_profile_array(name: str, profile: list, output_dir: Path, filename: str) -> None:
    """Emit a 2D profile array to a .scad file.

    If the last point duplicates the first (closed path), it is stripped
    since OpenSCAD's polygon() closes automatically.
    """
    pts = profile[:-1] if _is_closed(profile) else profile
    lines = [HEADER]
    lines.append(f"{name} = [\n")
    for i, pt in enumerate(pts):
        comma = "," if i < len(pts) - 1 else ""
        lines.append(f"  {_format_point_2d(pt)}{comma}\n")
    lines.append("];\n")
    (output_dir / filename).write_text("".join(lines))


@emitter("mug_profiles")
def _emit_mug_profiles(data: dict[str, Any], output_dir: Path) -> None:
    """Emit mug_outer_profile.scad and mug_inner_profile.scad."""
    _emit_profile_array(
        "mug_outer_profile", data["mug_outer_profile"],
        output_dir, "mug_outer_profile.scad",
    )
    _emit_profile_array(
        "mug_inner_profile", data["mug_inner_profile"],
        output_dir, "mug_inner_profile.scad",
    )


@emitter("handle_stations")
def _emit_handle_stations(data: dict[str, Any], output_dir: Path) -> None:
    """Emit handle_stations.scad."""
    stations = data["handle_stations"]  # list of list of [x,y,z]
    lines = [HEADER]
    lines.append("handle_stations = [\n")
    for si, poly in enumerate(stations):
        lines.append("  [\n")
        for pi, pt in enumerate(poly):
            comma = "," if pi < len(poly) - 1 else ""
            lines.append(f"    {_format_point_3d(pt)}{comma}\n")
        comma = "," if si < len(stations) - 1 else ""
        lines.append(f"  ]{comma}\n")
    lines.append("];\n")

    (output_dir / "handle_stations.scad").write_text("".join(lines))


@emitter("handle_path")
def _emit_handle_path(data: dict[str, Any], output_dir: Path) -> None:
    """Emit handle_path.scad (debug centroids)."""
    if "handle_path" not in data:
        return
    path = data["handle_path"]  # list of [x,y,z]
    lines = [HEADER]
    lines.append("handle_path = [\n")
    for i, pt in enumerate(path):
        comma = "," if i < len(path) - 1 else ""
        lines.append(f"  {_format_point_3d(pt)}{comma}\n")
    lines.append("];\n")

    (output_dir / "handle_path.scad").write_text("".join(lines))


@emitter("mug_params")
def _emit_mug_params(data: dict[str, Any], output_dir: Path) -> None:
    """Emit mug_params.scad with OpenSCAD parameters."""
    params = data["mug_params"]  # dict with fn, fa, fs, bbox, etc.
    lines = [HEADER]

    if params.get("fn", 0) > 0:
        lines.append(f"$fn = {params['fn']};\n")
    else:
        lines.append(f"$fa = {params.get('fa', 12)};\n")
        lines.append(f"$fs = {params.get('fs', 2)};\n")

    if "bbox" in params:
        bb = params["bbox"]
        lines.append(f"mug_bbox = [{_format_point_3d(bb[0])}, {_format_point_3d(bb[1])}];\n")

    if "axis_x" in params:
        lines.append(f"mug_axis_x = {params['axis_x']:.6f};\n")

    if "clay_shrinkage_pct" in params:
        lines.append(f"clay_shrinkage_pct = {params['clay_shrinkage_pct']:.1f};\n")

    # Mould parameters
    for key in ("plaster_thickness", "wall_thickness", "natch_radius"):
        if key in params:
            lines.append(f"{key} = {params[key]:.6f};\n")

    if "mould_type" in params:
        lines.append(f"mould_type = {params['mould_type']};\n")

    for key in ("foot_concavity_z", "foot_concavity_radius"):
        if key in params:
            lines.append(f"{key} = {params[key]:.6f};\n")

    (output_dir / "mug_params.scad").write_text("".join(lines))


@emitter("static_files")
def _emit_static_files(data: dict[str, Any], output_dir: Path) -> None:
    """Copy static .scad files from the bundled scad/ directory."""
    scad_src = Path(__file__).resolve().parent.parent / "scad"
    if not scad_src.is_dir():
        return

    for src_file in scad_src.rglob("*.scad"):
        rel = src_file.relative_to(scad_src)
        dst = output_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_file, dst)


def run_all_emitters(data: dict[str, Any], output_dir: str | Path) -> list[str]:
    """Run all registered emitters.

    Args:
        data: Dict containing keys expected by each emitter.
        output_dir: Directory to write output files.

    Returns:
        List of emitter names that were run.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    ran = []
    for name, fn in _emitters.items():
        fn(data, out)
        ran.append(name)
    return ran
