"""OpenSCAD data file writer with registry pattern."""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Any, Callable

HEADER = "// Auto-generated by mug-generator — do not edit\n\n"

# Registry of emitters: name → (fn, needs)
_emitters: dict[str, tuple[Callable[[dict[str, Any], Path], None],
                           Callable[[dict[str, bool]], bool] | None]] = {}


def emitter(name: str, needs: Callable[[dict[str, bool]], bool] | None = None):
    """Decorator to register an emitter function.

    ``needs`` is an optional predicate taking the exports dict; when it
    returns False the emitter is skipped.
    """
    def wrapper(fn: Callable[[dict[str, Any], Path], None]):
        _emitters[name] = (fn, needs)
        return fn
    return wrapper


# Map from static .scad filename → export flag that enables it.
# Files not in this map are always copied (shared helpers).
EXPORT_TO_SCAD: dict[str, str] = {
    "mug.scad": "prototype",
    "case_mould_original.scad": "case_mould",
    "case_mould_efficient.scad": "case_mould_efficient",
    "funnel.scad": "funnel",
    "slump_mould.scad": "slump_mould",
    "slump_mould_jiggering_rib.scad": "slump_rib",
    "hump_mould.scad": "hump_mould",
    "hump_mould_jiggering_rib.scad": "hump_rib",
}


def _any(exports: dict[str, bool], *keys: str) -> bool:
    return any(exports.get(k) for k in keys)


def _format_point_2d(pt: list[float] | tuple[float, ...]) -> str:
    return f"[{pt[0]:.6f}, {pt[1]:.6f}]"


def _format_point_3d(pt: list[float] | tuple[float, ...]) -> str:
    return f"[{pt[0]:.6f}, {pt[1]:.6f}, {pt[2]:.6f}]"


def _is_closed(profile: list) -> bool:
    """Check if a profile's last point duplicates the first."""
    if len(profile) < 2:
        return False
    first, last = profile[0], profile[-1]
    return abs(first[0] - last[0]) < 1e-6 and abs(first[1] - last[1]) < 1e-6


def _emit_profile_array(name: str, profile: list, output_dir: Path, filename: str) -> None:
    """Emit a 2D profile array to a .scad file.

    If the last point duplicates the first (closed path), it is stripped
    since OpenSCAD's polygon() closes automatically.
    """
    pts = profile[:-1] if _is_closed(profile) else profile
    lines = [HEADER]
    lines.append(f"{name} = [\n")
    for i, pt in enumerate(pts):
        comma = "," if i < len(pts) - 1 else ""
        lines.append(f"  {_format_point_2d(pt)}{comma}\n")
    lines.append("];\n")
    (output_dir / filename).write_text("".join(lines))


@emitter("mug_body_profile")
def _emit_mug_body_profile(data: dict[str, Any], output_dir: Path) -> None:
    """Emit mug_body_profile.scad with the body bezpath."""
    bez = data["mug_body_profile_bez"]
    closed = bool(data.get("mug_body_profile_closed"))
    lines = [HEADER, "mug_body_profile_bez = [\n"]
    for i, pt in enumerate(bez):
        comma = "," if i < len(bez) - 1 else ""
        lines.append(f"  {_format_point_2d(pt)}{comma}\n")
    lines.append("];\n")
    lines.append(f"mug_body_profile_closed = {'true' if closed else 'false'};\n")
    (output_dir / "mug_body_profile.scad").write_text("".join(lines))


@emitter(
    "handle_bezpaths",
    needs=lambda ex: _any(ex, "prototype", "case_mould", "case_mould_efficient"),
)
def _emit_handle_bezpaths(data: dict[str, Any], output_dir: Path) -> None:
    """Emit handle_bezpaths.scad with raw rail / profile bezpaths."""
    inner_bez = data.get("handle_inner_rail_bez")
    outer_bez = data.get("handle_outer_rail_bez")
    side_rail_polyline = data.get("handle_side_rail_polyline")
    profile_bez = data.get("handle_profile_bez")
    n_stations_data = data.get("handle_n_stations")

    lines = [HEADER]

    def _emit_2d_array(name, pts):
        lines.append(f"{name} = [\n")
        for i, pt in enumerate(pts):
            comma = "," if i < len(pts) - 1 else ""
            lines.append(f"  {_format_point_2d(pt)}{comma}\n")
        lines.append("];\n")

    if inner_bez and outer_bez and profile_bez:
        _emit_2d_array("handle_inner_rail_bez", inner_bez)
        _emit_2d_array("handle_outer_rail_bez", outer_bez)
        _emit_2d_array("handle_profile_bez", profile_bez)
        if side_rail_polyline:
            _emit_2d_array("handle_side_rail_polyline", side_rail_polyline)
        else:
            lines.append("handle_side_rail_polyline = [];\n")
        if n_stations_data is not None:
            lines.append(f"handle_n_stations = {int(n_stations_data)};\n")
    else:
        lines.append("handle_inner_rail_bez = [];\n")
        lines.append("handle_outer_rail_bez = [];\n")
        lines.append("handle_profile_bez = [];\n")
        lines.append("handle_side_rail_polyline = [];\n")
        lines.append("handle_n_stations = 0;\n")

    (output_dir / "handle_bezpaths.scad").write_text("".join(lines))


@emitter("mug_params")
def _emit_mug_params(data: dict[str, Any], output_dir: Path) -> None:
    """Emit mug_params.scad with OpenSCAD parameters.

    Only parameters consumed by exported .scad files are written, so
    an export selection of just, say, the funnel doesn't leak mould or
    rib settings into the generated file.
    """
    params = data["mug_params"]  # dict with fn, fa, fs, bbox, etc.
    exports = data.get("exports")

    if exports is None:
        # No selection supplied — emit everything (backwards-compatible).
        want_case_mould = want_case_mould_efficient = True
        want_mould_any = want_filler_tube = True
        want_funnel = want_mark = want_rib = want_hump_rib = True
    else:
        want_case_mould = _any(exports, "case_mould", "case_mould_efficient")
        want_case_mould_efficient = exports.get("case_mould_efficient", False)
        want_mould_any = _any(exports, "case_mould", "case_mould_efficient", "slump_mould", "hump_mould")
        want_filler_tube = _any(exports, "case_mould", "case_mould_efficient", "funnel")
        want_funnel = exports.get("funnel", False)
        want_mark = _any(exports, "prototype", "case_mould", "case_mould_efficient", "slump_mould")
        want_rib = _any(exports, "slump_rib", "hump_rib")
        want_hump_rib = exports.get("hump_rib", False)

    lines = [HEADER]

    if params.get("fn", 0) > 0:
        lines.append(f"$fn = {params['fn']};\n")
    else:
        lines.append(f"$fa = {params.get('fa', 12)};\n")
        lines.append(f"$fs = {params.get('fs', 2)};\n")

    if "bbox" in params:
        bb = params["bbox"]
        lines.append(f"mug_bbox = [{_format_point_3d(bb[0])}, {_format_point_3d(bb[1])}];\n")

    lines.append(f"handle_enabled = {'true' if params.get('handle_enabled') else 'false'};\n")

    if "axis_x" in params:
        lines.append(f"mug_axis_x = {params['axis_x']:.6f};\n")

    if "clay_shrinkage_pct" in params:
        lines.append(f"clay_shrinkage_pct = {params['clay_shrinkage_pct']:.1f};\n")

    # Shared plaster-mould parameters (used by case, slump, and hump moulds)
    if want_mould_any:
        for key in ("plaster_thickness", "wall_thickness"):
            if key in params:
                lines.append(f"{key} = {params[key]:.6f};\n")

    # filler_tube_height / angle is consumed by the case mould and the funnel
    if want_filler_tube and "filler_tube_height" in params:
        lines.append(f"filler_tube_height = {params['filler_tube_height']:.6f};\n")
    if want_filler_tube and "filler_tube_angle" in params:
        lines.append(f"filler_tube_angle = {params['filler_tube_angle']:.6f};\n")

    # Case-mould-only parameters
    if want_case_mould:
        if "alignment_type" in params:
            lines.append(f'alignment_type = "{params["alignment_type"]}";\n')
        for key in ("natch_radius", "key_tolerance"):
            if key in params:
                lines.append(f"{key} = {params[key]:.6f};\n")
        for key in ("foot_concavity_z", "foot_concavity_radius"):
            if key in params:
                lines.append(f"{key} = {params[key]:.6f};\n")
        if "mould_type" in params:
            lines.append(f"mould_type = {params['mould_type']};\n")

    # Case-mould-efficient derived parameters
    if want_case_mould_efficient:
        if "needs_base" in params:
            lines.append(
                f"needs_base = {'true' if params['needs_base'] else 'false'};\n"
            )
        for key in ("z_min_scaled", "z_lip_scaled", "lip_r_scaled"):
            if key in params:
                lines.append(f"{key} = {params[key]:.6f};\n")

    # Funnel parameters
    if want_funnel:
        for key in ("funnel_wall_angle", "funnel_wall", "flange_width",
                     "breather_hole_dia"):
            if key in params:
                lines.append(f"{key} = {params[key]:.6f};\n")
        if "breather_hole_count" in params:
            lines.append(f"breather_hole_count = {params['breather_hole_count']};\n")

    # Maker's mark parameters
    if want_mark:
        lines.append(f"mark_enabled = {'true' if params.get('mark_enabled') else 'false'};\n")
        lines.append(f"mark_depth = {params.get('mark_depth', 1.0):.6f};\n")
        lines.append(f"mark_inset = {'true' if params.get('mark_inset', True) else 'false'};\n")
        lines.append(f"mark_draft_angle = {params.get('mark_draft_angle', 45.0):.6f};\n")
        lines.append(f"mark_layer_height = {params.get('mark_layer_height', 0.2):.6f};\n")
        lines.append(f"mark_fa = {params.get('mark_fa', 12):.6f};\n")
        lines.append(f"mark_fs = {params.get('mark_fs', 0.25):.6f};\n")

    # Jiggering rib parameters
    if want_rib:
        for key in ("rib_thickness", "rib_taper", "rib_margin"):
            if key in params:
                lines.append(f"{key} = {params[key]:.6f};\n")
        if "wheel_direction" in params:
            lines.append(f'wheel_direction = "{params["wheel_direction"]}";\n')
    if want_hump_rib and "hump_rib_direction" in params:
        lines.append(f'hump_rib_direction = "{params["hump_rib_direction"]}";\n')

    (output_dir / "mug_params.scad").write_text("".join(lines))


@emitter(
    "mark_polygon",
    needs=lambda ex: _any(ex, "prototype", "case_mould", "case_mould_efficient", "slump_mould"),
)
def _emit_mark_polygon(data: dict[str, Any], output_dir: Path) -> None:
    """Emit mark_polygon.scad with flat points + paths arrays.

    OpenSCAD's ``polygon(points, paths)`` handles even-odd fill
    natively, so we emit a single flat points array and a paths
    array of index lists (one per subpath).  This avoids the
    skin() + difference() approach that produced non-manifold meshes.
    """
    bezpaths = data.get("mark_bezpaths")
    lines = [HEADER]

    if not bezpaths:
        lines.append("mark_bezpaths = [];\n")
    else:
        lines.append("mark_bezpaths = [\n")
        for bi, bez in enumerate(bezpaths):
            outer_comma = "," if bi < len(bezpaths) - 1 else ""
            lines.append("  [\n")
            for pi, pt in enumerate(bez):
                comma = "," if pi < len(bez) - 1 else ""
                lines.append(f"    {_format_point_2d(pt)}{comma}\n")
            lines.append(f"  ]{outer_comma}\n")
        lines.append("];\n")

    (output_dir / "mark_polygon.scad").write_text("".join(lines))


@emitter("static_files")
def _emit_static_files(data: dict[str, Any], output_dir: Path) -> None:
    """Copy static .scad files from the bundled scad/ directory.

    Files listed in ``EXPORT_TO_SCAD`` are only copied when the
    corresponding export flag is set.  Files outside the map (shared
    helpers) are always copied.
    """
    scad_src = Path(__file__).resolve().parent.parent / "scad"
    if not scad_src.is_dir():
        return

    exports = data.get("exports")

    for src_file in scad_src.rglob("*.scad"):
        rel = src_file.relative_to(scad_src)
        flag = EXPORT_TO_SCAD.get(str(rel))
        if flag is not None and exports is not None and not exports.get(flag, True):
            continue
        dst = output_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_file, dst)


def run_all_emitters(data: dict[str, Any], output_dir: str | Path) -> list[str]:
    """Run all registered emitters, skipping those whose ``needs`` predicate
    rejects the current exports set.

    Args:
        data: Dict containing keys expected by each emitter.  May include
            an ``exports`` sub-dict of bool flags.
        output_dir: Directory to write output files.

    Returns:
        List of emitter names that were run.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    exports = data.get("exports")

    ran = []
    for name, (fn, needs) in _emitters.items():
        if exports is not None and needs is not None and not needs(exports):
            continue
        fn(data, out)
        ran.append(name)
    return ran
